# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  #
  config.vm.communicator = "winrm"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "https://www.dropbox.com/s/qznpu808y9hz75j/windows7.box?raw=1"
  
  config.vm.network "private_network", ip: "10.0.0.100"

  config.vm.guest = :windows
  config.vm.network :forwarded_port, guest: 3389, host: 3389

  config.vm.provision :shell, :path => "rdaccess.bat"

end
