# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
  end

  #Add mongodb docker image
  #config.vm.provision "docker",
  #  images: ["dockerfile/mongodb"]

  config.vm.provision "docker" do |d|
    d.build_image "./", args: "-t ubuntu/mongodb"
  end

  #Run mongodb
  config.vm.provision "docker" do |d|
    d.run "ubuntu/mongo"
  end

  # Create a forwarded port mapping which allows access to a specific port
  # which allows the guest mongodb instance on port 27017 to be access from the host
  config.vm.network "forwarded_port", guest: 27017, host: 27018

end
