---
- hosts: all
  sudo: yes
  tasks:
  - name: install git
    apt: pkg=git state=latest
  - name: Add java repositories
    apt_repository: repo='ppa:webupd8team/java' update_cache=yes
  - name: Shell accepted oracle license
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  - name: Install java7
    apt: pkg=oracle-java7-installer update_cache=yes state=installed
